sell/urls.py
from django.urls import path
from . import views

app_name = 'sell'

urlpatterns = [
    path("", views.MainPageView.as_view(), name='home'),
]

sellsite/urls.py
from django.contrib.staticfiles.storage import  staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("images/favicon.ico"))),
    path('', include('sell.urls')),
]

sell/models.py
from django.db import models

# Create your models here.

sell/views.py
from django.views.generic import TemplateView


class MainPageView(TemplateView):
    template_name = 'home.html'

templates/home.html
{% extends "layout.html" %}
{% load static %}

{% block title %} Home|SellYourTing {% endblock %}

{% block content %}

{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Chango&family=IBM+Plex+Sans:wght@500&family=Open+Sans:wght@600&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    {% block styles %} {% endblock %}
</head>
<body>
    <div class="main-container">
        <header class="head-title">
            <h1>Welcome to SellYourTing</h1>
            <p>Here you can sell whatever you want at no charge</p>
        </header>

        <nav class="main-nav">
            <button id="btn" class="mobile-nav-show">&#10140</button>
            <ul id="display-none" class="nav-list">
                <li><a href="{% url 'sell:home' %}">Home</a></li>
                <li><a href="#">Shop</a></li>
                <li><a href="#">About</a></li>
            </ul>
        </nav>
    </div>
    {% block content %} {% endblock %}

<script src="{% static 'js/main.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>